### ISSUE TITLE
Integrate GitHub Markdown Syntax library to your webpage

### ISSUE THREAD

**Issue by domalex** [FydeOS/fydetabduo-wiki#12]
Please include GitHub's Markdown syntax library to your website. Oherwise pages wont render properly.

Example: https://wiki.fydetabduo.com/flashing_the_fydetab_duo

**Comment by Lorde627** [comment]
Could you specify which part is not rendering correctly?

**Comment by domalex** [comment]
I realized that Alerts are not properly rendered but there might be other elements too.

Reference: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by Lorde627** [comment]
Please refer to the [Admonitions syntax](https://docusaurus.io/docs/markdown-features/admonitions) documentation.
