### ISSUE TITLE
upgrade_tool vs rkdeveloptool

### ISSUE THREAD

**Issue by WhyNotHugo** [FydeOS/fydetabduo-wiki#13]
The wiki [currently suggests using `upgrade_tool`](https://github.com/FydeOS/fydetabduo-wiki/blob/main/docs/3.Flashing%20the%20Fydetab%20Duo.md#using-linux), a proprietary binary-only tool that apparently only works on Debian/Ubuntu.

It also mentions `rkdeveloptool` as a better alternative, which is open source and available in several distributions. It also works fine for flashing the FydeTab Duo.

I'm confused by the fact that `rkdeveloptool` is presented as a better, more reliable alternative, but the instructions only explain how to use `upgrade_tool`.

What's the reason for preferring `upgrade_tool`?

**Comment by Lorde627** [comment]
upgrade_tool is easy to use—you can download it and run it on other Linux distributions and even macOS. rkdeveloptool needs to be compiled and installed, which can be tricky for non-coders. That's why we went with upgrade_tool. If you find a better option, feel free to submit a PR~
